<?php /* @var $this \App\Hint\HelperManager */ ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="utf-8" lang="utf-8">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=0" />
        <title>MC 用户手册</title>
        <link rel="shortcut icon" href="<?php echo $this->image('favicon.ico')?>" type="image/x-icon" />
        <?php echo $this->css('common.css')->wrap()?>
    </head>
    <body>
        <?php echo $__header?>
        <div id="content">
            <?php echo $__content?>
        </div>
        <?php echo $__footer?>
    </body>
</html>