<?php /* @var $this \App\Hint\HelperManager */ ?>
<h1><?php echo $title?></h1>
<p>控制器是应用程序的心脏，因为它们决定如何处理 HTTP 请求</p>
<ul>
    <li><a href="#what">什么是控制器?</a></li>
    <li><a href="#hello">Hello World!</a></li>
    <li><a href="#method">方法</a></li>
</ul>

<a name="what"><h2>什么是控制器?</h2></a>
<p><dfn>简而言之，一个控制器就是一个类文件，是以一种能够和 URI 关联在一起的方式来命名的</dfn></p>
<p>假设这个 URI：</p>
<code>example.com/index.php/<var>my-test</var>/<var>say</var></code>
<p>在上面的例子中，MC 将尝试寻找并调用一个名为 <samp>MyTestController</samp> 控制器中的 <samp>sayAction</samp> 方法</p>

<a name="hello"><h2>让我们试一试：Hello World!</h2></a>
<p>我们来创建一个简单的控制器，以便更直观地了解其工作原理。使用你的文本编辑器，创建一个名为 <dfn>MyTestController.php</dfn> 的文件，然后输入下列代码：</p>
<code>
&lt;?php<br />
<br />
namespace&nbsp;App\Controller;<br />
<br />
class&nbsp;<var>MyTestController</var>&nbsp;extends&nbsp;AbstractActionController<br />
{<br />
&nbsp;&nbsp;&nbsp;&nbsp;public&nbsp;function&nbsp;<var>sayAction()</var><br />
&nbsp;&nbsp;&nbsp;&nbsp;{<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;'Hello&nbsp;World!';<br />
&nbsp;&nbsp;&nbsp;&nbsp;}<br />
}
</code>
<p>然后将这个文件保存到你的 <dfn>App/Class/Controller/</dfn> 文件夹中</p>
<p>现在使用类似这样的 URL 访问你的站点：</p>
<code>example.com/index.php/<var>my-test</var>/<var>say</var></code>
<p>如果你做的没错，你应该看到 <samp>Hello World!</samp></p>
<p class="important">注意：类名和文件名同名，必须以大写字母开头，采用驼峰命名，后面紧跟 Controller。就像这样 <strong>MyTestController</strong></p>

<a name="method"><h2>方法</h2></a>
<p><dfn>URI 的第二部分是用来决定调用控制器中哪个方法的</dfn></p>
<p>我们再来试试，在你的控制器中加入一个新的方法：</p>
<code>
&lt;?php<br />
<br />
namespace&nbsp;App\Controller;<br />
<br />
class&nbsp;MyTestController&nbsp;extends&nbsp;AbstractActionController<br />
{<br />
&nbsp;&nbsp;&nbsp;&nbsp;public&nbsp;function&nbsp;sayAction()<br />
&nbsp;&nbsp;&nbsp;&nbsp;{<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;'Hello&nbsp;World!';<br />
&nbsp;&nbsp;&nbsp;&nbsp;}<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;public&nbsp;function&nbsp;<var>hereAction()</var><br />
&nbsp;&nbsp;&nbsp;&nbsp;{<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;echo&nbsp;'See&nbsp;here.';<br />
&nbsp;&nbsp;&nbsp;&nbsp;}<br />
}
</code>
<p>现在在地址栏中输入下面的内容来访问 <dfn>hereAction</dfn> 方法：</p>
<code>example.com/index.php/<var>my-test</var>/<var>here</var></code>
<p>你应该看到新的信息了 <samp>See here.</samp></p>
<p class="important">注意：方法名必须以小写字母开头，采用驼峰命名，后面紧跟 Action。换句话说，这是有效的 <strong>sayAction</strong></p>