<?php /* @var $this \App\Hint\HelperManager */ ?>
<h1><?php echo $title?></h1>
<p>字符串工具为你提供对字符串类型的各种函数</p>

<h2>载入字符串工具</h2>
<p>通过 <a href="<?php echo $this->url('core/autoloader')?>">自动加载类</a> 载入字符串工具：</p>
<code>use Core\Utils\Str;</code>

<h2>concat($str, $seperator = ' ')</h2>
<p>连接字符串：</p>
<code>
    $url .= Str::concat($query, '?'); // <var>$url<samp>?</samp>$query</var><br />
    $sql .= Str::concat('LIMIT 0, 1'); // <var>$sql LIMIT 0, 1</var>
</code>